env:
  browser: true
  es2021: true
  node: true
  jest: true
extends: eslint:recommended
overrides: []
globals:
  log: 'writable'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins: ['unused-imports']
rules: {
  "no-control-regex": 0,
  "no-unused-vars": "off",
  "unused-imports/no-unused-imports": "error",
  "unused-imports/no-unused-vars": [
    "warn",
    {
      "vars": "all",
      "varsIgnorePattern": "^_",
      "args": "after-used",
      "argsIgnorePattern": "^_"
    }
  ]
}
