{
 "title": "Logs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Grid Java API",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=~\"/.*grid-java-api.*\"} |= ``"
    }
   ]
  },
  {
   "title": "Grid Coordinator",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=~\"/.*grid-java-coordinator.*\"} |= ``"
    }
   ]
  },
  {
   "title": "Webconsole",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=~\"/.*webconsole.*\"} |= ``"
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=~\"/.*zookeeper.*\"} |= ``"
    }
   ]
  }
 ]
}